---
title: "ProjectCK"
author: "Nguyen Minh Thu"
date: "2026-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, librarys}
library(corrplot)
library(ggplot2)
library(ggcorrplot)
library(car)
library(dplyr)
library(tidyr)
library(reshape2)
library(gridExtra)
library(patchwork)

```

```{r, loaddatabase}
# NHẬP DỮ LIỆU
data <- read.csv("heart_disease_dataset_clean.csv")
View(data)
```

```{r}
# PHÂN BỐ BIẾN MỤC TIÊU
data %>%
  count(target)%>%
  mutate(percent = n / sum(n) * 100)

ggplot(data, aes(x = factor(target))) +
  geom_bar(fill = "steelblue") +
  labs(title = "Phân bổ biến mục tiêu", x = "Target", y = "Số lượng") +
  theme_minimal()
```

<p>
# PHÂN BỐ BIẾN ĐỊNH LƯỢNG
```{r}
# PHÂN BỐ BIẾN AGE
ggplot(data, aes(x = age)) +
  geom_histogram(bins = 10, fill = "steelblue", color = "black") +
  labs(
    title = "Phân bố biến Age",
    x = "Tuổi",
    y = "Số lượng"
  ) +
  theme_minimal()

# PHÂN BỐ BIẾN TRESTBPS
ggplot(data, aes(x = trestbps)) +
  geom_histogram(bins = 10, fill = "steelblue",color = "black") +
  labs(
    title = "Phân bố biến Trestbps",
    x = "Huyết áp lúc nghỉ",
    y = "Số lượng"
  ) +
  theme_minimal()

# PHÂN BỐ BIẾN CHOL

ggplot(data, aes(x = chol)) +
  geom_histogram(bins = 10, fill = "steelblue",color = "black") +
  labs(
    title = "Phân bố biến Chol",
    x = "Nồng độ cholesterol toàn phần trong máu",
    y = "Số lượng"
  ) +
  theme_minimal()

# PHÂN BỐ BIẾN THALACH
ggplot(data, aes(x = thalach)) +
  geom_histogram(bins = 10, fill = "steelblue",color = "black") +
  labs(
    title = "Phân bố biến Thalach",
    x = "Nhịp tim tối đa đạt được trong quá trình kiểm tra hoặc vận động",
    y = "Số lượng"
  ) +
  theme_minimal()

# PHÂN BỐ BIẾN OLDPEAK
ggplot(data, aes(x = oldpeak)) +
  geom_histogram(bins = 10, fill = "steelblue",color = "black") +
  labs(
    title = "Phân bố biến Oldpeak",
    x = "Chỉ số phản ánh mức độ ảnh hưởng của hoạt động gắng sức lên tim",
    y = "Số lượng"
  ) +
  theme_minimal()
```
<p>
# PHÂN BỐ BIẾN ĐỊNH TÍNH
```{r}
# PHÂN BỐ BIẾN SEX
data %>%
  count(sex) %>%
  mutate(percent = n / sum(n) * 100)

ggplot(data, aes(x = factor(sex))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Giới tính",
    y = "Số lượng",
    title = "Phân bố biến sex")+
  theme_minimal()

# PHÂN BỐ BIẾN CP
data %>%
  count(cp) %>%
  mutate(percent = n / sum(n) * 100)

ggplot(data, aes(x = factor(cp))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Loại đau ngực",
    y = "Số lượng",
    title = "Phân bố biến cp")+
  theme_minimal()


# PHÂN BỐ BIẾN FBS
data %>%
  count(fbs) %>%
  mutate(percent = n / sum(n) * 100)

ggplot(data, aes(x = factor(fbs))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Đường huyết lúc đói",
    y = "Số lượng",
    title = "Phân bố biến fbs")+
  theme_minimal()


# PHÂN BỐ BIẾN RESTECG
data %>%
  count(restecg) %>%
  mutate(percent = n / sum(n) * 100) 

ggplot(data, aes(x = factor(restecg))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Điện tâm đồ lúc nghỉ",
    y = "Số lượng",
    title = "Phân bố biến restecg")+
  theme_minimal()

# PHÂN BỐ BIẾN EXANG
data %>%
  count(exang) %>%
  mutate(percent = n / sum(n) * 100) 

ggplot(data, aes(x = factor(exang))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Có đau thắt ngực do vận động hay không",
    y = "Số lượng",
    title = "Phân bố biến exang")+
  theme_minimal()

# PHÂN BỐ BIẾN SLOPE
data %>%
  count(slope) %>%
  mutate(percent = n / sum(n) * 100) 

ggplot(data, aes(x = factor(slope))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Độ dốc của đoạn ST khi gắng sức",
    y = "Số lượng",
    title = "Phân bố biến slope")+
  theme_minimal()

# PHÂN BỐ BIẾN CA
data %>%
  count(ca) %>%
  mutate(percent = n / sum(n) * 100) 

ggplot(data, aes(x = factor(ca))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Số lượng động mạch được nhuộm màu bằng phương pháp chụp mạch vành",
    y = "Số lượng",
    title = "Phân bố biến ca")+
  theme_minimal()

# PHÂN BỐ BIẾN THAL
data %>%
  count(thal) %>%
  mutate(percent = n / sum(n) * 100) 

ggplot(data, aes(x = factor(thal))) +
  geom_bar(fill = "steelblue") +
  labs( 
    x = "Thalassemia",
    y = "Số lượng",
    title = "Phân bố biến thal") +
  theme_minimal()
```
<p>
# PHÂN TÍCH TƯƠNG QUAN GIỮA CÁC BIẾN
```{r}
# MA TRẬN TƯƠNG QUAN PEARSON

num_data <- data[, sapply(data, is.numeric)]

corr_matrix <- cor(num_data, method = "pearson")
round(corr_matrix, 3)

corr_test <- cor_pmat(num_data)
round(corr_test, 4)

# TƯƠNG QUAN GIỮA CÁC BIẾN VÀ TARGET

cor_target <- data.frame(
  Variable = rownames(corr_matrix),
  Correlation = corr_matrix[, "target"]
) %>%
  filter(Variable != "target") %>%
  mutate(
    Correlation = round(Correlation, 3),

     Group = case_when(
      abs(Correlation) < 0.2 ~ "Rất yếu",
      abs(Correlation) < 0.4 ~ "Yếu",
      abs(Correlation) < 0.6 ~ "Trung bình",
      abs(Correlation) < 0.8 ~ "Mạnh",
      TRUE ~ "Rất mạnh"
    ),

    Direction = case_when(
      Correlation > 0 ~ "Thuận",
      Correlation < 0 ~ "Nghịch",
      TRUE ~ "Không có"
    )
  ) %>%
  arrange(desc(Correlation))

cor_target

# TƯƠNG QUAN GIỮA CÁC BIẾN SỐ

num_vars <- data[, c(
  "age",
  "trestbps",
  "chol",
  "thalach",
  "oldpeak"
)]

cor_matrix_num <- cor(num_vars)

cor_pairs <- melt(cor_matrix_num) %>%
  mutate(
    Var1 = as.character(Var1),
    Var2 = as.character(Var2)
  ) %>%
  filter(Var1 < Var2) %>%
  mutate(
    Correlation = round(value, 3),
 Group = case_when(
      abs(Correlation) < 0.2 ~ "Rất yếu",
      abs(Correlation) < 0.4 ~ "Yếu",
      abs(Correlation) < 0.6 ~ "Trung bình",
      abs(Correlation) < 0.8 ~ "Mạnh",
      TRUE ~ "Rất mạnh"
    ),

    Direction = case_when(
      Correlation > 0 ~ "Thuận",
      Correlation < 0 ~ "Nghịch",
      TRUE ~ "Không có"
    )
  ) %>%
  select(Var1, Var2, Correlation,Group) %>%
  arrange(desc(abs(Correlation)))

cor_pairs
```

```{r warning=FALSE}
# TRỰC QUAN HÓA BẰNG HEATMAP
ggcorrplot(
  corr_matrix,
  hc.order = TRUE,
  type = "lower",
  lab = TRUE,
  lab_size = 2.3,
  show.diag = FALSE
) +
  labs(title = "Ma trận tương quan giữa các biến")
```

<p>
# BIỂU ĐỒ TƯƠNG QUAN GIỮA CÁC BIẾN
```{r}
# BIỂU ĐỒ TƯƠNG QUAN GIỮA BIẾN AGE VÀ THALACH
ggplot(data, aes(x = age, y = thalach)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Mối quan hệ giữa Age và Thalach",
    x = "Age",
    y = "Thalach"
  ) +
  theme_minimal()

# BIỂU ĐỒ TƯƠNG QUAN GIỮA BIẾN AGE VÀ COL
ggplot(data, aes(x = age, y = chol)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Mối quan hệ giữa Age và Chol",
    x = "Age",
    y = "Chol"
  ) +
  theme_minimal()

# BIỂU ĐỒ TƯƠNG QUAN GIỮA BIẾN CHOL VA THALACH
ggplot(data, aes(x = chol, y = thalach)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Mối quan hệ giữa Chol và Thalach",
    x = "Chol",
    y = "Thalach"
  ) +
  theme_minimal()

# BIỂU ĐỒ TƯƠNG QUAN GIỮA BIẾN OLDPEAK VÀ THALACH
ggplot(data, aes(x = oldpeak, y = thalach)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(
    title = "Mối quan hệ giữa Oldpeak và Thalach",
    x = "Oldpeak",
    y = "Thalach"
  ) +
  theme_minimal()
```

```{r}
# PHÂN TÍCH ĐA CỘNG TUYẾN
model_vif <- lm(
  target ~ .,
  data = data
)

vif(model_vif)
```
<p>
# SO SÁNH GIỮA NHÓM MẮC BỆNH VÀ NHÓM KHÔNG MẮC BỆNH
<p>
# SO SÁNH CÁC BIẾN ĐỊNH LƯỢNG
```{r}
# BIỂU ĐỒ HỘP TUỔI THEO TÌNH TRẠNG BỆNH
BD1 <- ggplot(data,
       aes(x = factor(target), y = age, fill = factor(target))) +
  geom_boxplot() +
  labs(
    x = "Tình trạng bệnh tim",
    y = "Tuổi",
    fill = "Target"
  ) +
  theme_minimal()

# BIỂU ĐỒ HỘP HUYẾT ÁP LÚC NGHỈ THEO TÌNH TRẠNG BỆNH
BD2 <- ggplot(data, aes(x = factor(target), y = trestbps, fill = factor(target))) +
  geom_boxplot() +
  labs(
    x = "Tình trạng bệnh tim",
    y = "Huyết áp lúc nghỉ"
  ) +
  theme_minimal()

# BIỂU ĐỒ HỘP CHOLESTEROL THEO TÌNH TRẠNG BỆNH 
BD3 <- ggplot(data, aes(x = factor(target), y = chol, fill = factor(target))) +
  geom_boxplot() +
  labs(
    x = "Tình trạng bệnh tim",
    y = "Nồng độ cholesterol"
  ) +
  theme_minimal()

# BIỂU ĐỒ HỘP NHỊP TIM TỐI ĐA THEO TÌNH TRẠNG BỆNH
BD4 <- ggplot(data, aes(x = factor(target), y = thalach, fill = factor(target))) +
  geom_boxplot() +
  labs(
    x = "Tình trạng bệnh tim",
    y = "Nhịp tim tối đa khi hoạt động"
  ) +
  theme_minimal()

# BIỂU ĐỒ HỘP OLDPEAK THEO TÌNH TRẠNG BỆNH
BD5 <- ggplot(data, aes(x = factor(target), y = oldpeak, fill = factor(target))) +
  geom_boxplot() +
  labs(
    x = "Tình trạng bệnh tim",
    y = "Chỉ số hoạt động gắng sức lên tim"
  ) +
  theme_minimal()

(BD1 + BD2 + BD3) /
(BD4 + BD5)
plot_annotation(
  title = "SO SÁNH CÁC BIẾN ĐỊNH LƯỢNG THEO NHÓM MẮC BỆNH VÀ KHÔNG MẮC BỆNH"
)
```
<p>
# SO SÁNH CÁC BIẾN PHÂN LOẠI
```{r}
# ĐỒ CỘT GIỚI TÍNH THEO TÌNH TRẠNG BỆNH
bd1 <-ggplot(data,
       aes(x = factor(sex,
                      labels = c("0", "1")),
           fill = factor(target,
                         labels = c("Không mắc bệnh",
                                    "Mắc bệnh")))) +
  geom_bar(position = "dodge") +
  labs(
    x = "Giới tính",
    y = "Số lượng",
    fill = "Tình trạng bệnh tim"
  ) +
  theme_minimal()

# ĐỒ CỘT LOẠI ĐAU NGỰC THEO TÌNH TRẠNG BỆNH
bd2 <- ggplot(data,
       aes(x = factor(cp,
                      labels = c("0", "1", "2", "3")),
           fill = factor(target,
                         labels = c("Không mắc bệnh",
                                    "Mắc bệnh")))) +
  geom_bar(position = "dodge") +
  labs(
    x = "Loại đau ngực",
    y = "Số lượng",
    fill = "Tình trạng bệnh tim"
  ) +
  theme_minimal()

# ĐỒ CỘT ĐAU THẮT NGỰC DO GẮNG SỨC THEO TÌNH TRẠNG BỆNH
bd3 <- ggplot(data,
       aes(x = factor(exang,
                      labels = c("0", "1")),
           fill = factor(target,
                         labels = c("Không mắc bệnh",
                                    "Mắc bệnh")))) +
  geom_bar(position = "dodge") +
  labs(
    x = "Đau thắt ngực do gắng sức",
    y = "Số lượng",
    fill = "Tình trạng bệnh tim"
  ) +
  theme_minimal()

# ĐỒ CỘT KẾT QUẢ THALASSEMIA THEO TÌNH TRẠNG BỆNH
bd4 <-ggplot(data,
       aes(x = factor(thal,
                      labels = c("0", "1","2")),
           fill = factor(target,
                         labels = c("Không mắc bệnh",
                                    "Mắc bệnh")))) +
  geom_bar(position = "dodge") +
  labs(
    x = "Kết quả Thalassemia",
    y = "Số lượng",
    fill = "Tình trạng bệnh tim"
  ) +
  theme_minimal()

# ĐỒ CỘT ĐỘ DỐC ĐOẠN ST THEO TÌNH TRẠNG BỆNH
bd5 <- ggplot(data,
       aes(x = factor(slope,
                      labels = c("0", "1","2")),
           fill = factor(target,
                         labels = c("Không mắc bệnh",
                                    "Mắc bệnh")))) +
  geom_bar(position = "dodge") +
  labs(
    x = "Độ dốc của đoạn ST khi gắng sức",
    y = "Số lượng",
    fill = "Tình trạng bệnh tim"
  ) +
  theme_minimal()

(bd1 + bd2) /
( bd3 + bd4 )/
  bd5
plot_annotation(
  title = "SO SÁNH CÁC BIẾN ĐỊNH TÍNH THEO NHÓM MẮC BỆNH VÀ KHÔNG MẮC BỆNH"
)
```

